spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: inventory-service
              uri: http://localhost:8082
              predicates:
                - Path=/inventory-service/**
              filters:
                - AddRequestHeader=MyHeader, MyValue
            - id: customer-service
              uri: http://localhost:8082
              predicates:
                - Path=/inventory-service/**
              filters:
                - AddRequestHeader=MyHeader, MyValue
            - id: order-service
              uri: http://localhost:8083
              predicates:
                - Path=/order-service/**
              filters:
                - AddRequestHeader=MyHeader, MyValue
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origin-patterns: "*"
                allowedMethods: GET, POST, PUT, DELETE, OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive